/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DarkGridInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimTimeoutVictory"
      | "confidentialProtocolId"
      | "createGame"
      | "getMatchInfo"
      | "getUsername"
      | "joinGame"
      | "movePiece"
      | "setUsername"
      | "usernames"
      | "viewBoard"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameCreated"
      | "GameJoined"
      | "MoveCommitted"
      | "UsernameSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimTimeoutVictory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createGame", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getMatchInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUsername",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "joinGame", values: [string]): string;
  encodeFunctionData(
    functionFragment: "movePiece",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setUsername", values: [string]): string;
  encodeFunctionData(
    functionFragment: "usernames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "viewBoard", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "claimTimeoutVictory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMatchInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "movePiece", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usernames", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "viewBoard", data: BytesLike): Result;
}

export namespace GameCreatedEvent {
  export type InputTuple = [matchId: string, creator: AddressLike];
  export type OutputTuple = [matchId: string, creator: string];
  export interface OutputObject {
    matchId: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameJoinedEvent {
  export type InputTuple = [
    matchId: string,
    white: AddressLike,
    shadow: AddressLike
  ];
  export type OutputTuple = [matchId: string, white: string, shadow: string];
  export interface OutputObject {
    matchId: string;
    white: string;
    shadow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveCommittedEvent {
  export type InputTuple = [
    matchId: string,
    player: AddressLike,
    from: BigNumberish,
    to: BigNumberish
  ];
  export type OutputTuple = [
    matchId: string,
    player: string,
    from: bigint,
    to: bigint
  ];
  export interface OutputObject {
    matchId: string;
    player: string;
    from: bigint;
    to: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsernameSetEvent {
  export type InputTuple = [player: AddressLike, username: string];
  export type OutputTuple = [player: string, username: string];
  export interface OutputObject {
    player: string;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DarkGrid extends BaseContract {
  connect(runner?: ContractRunner | null): DarkGrid;
  waitForDeployment(): Promise<this>;

  interface: DarkGridInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimTimeoutVictory: TypedContractMethod<
    [matchId: string],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createGame: TypedContractMethod<[matchId: string], [void], "nonpayable">;

  getMatchInfo: TypedContractMethod<
    [matchId: string],
    [[string, string, boolean, boolean, bigint, bigint, bigint]],
    "view"
  >;

  getUsername: TypedContractMethod<[player: AddressLike], [string], "view">;

  joinGame: TypedContractMethod<[matchId: string], [void], "nonpayable">;

  movePiece: TypedContractMethod<
    [matchId: string, from: BigNumberish, to: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUsername: TypedContractMethod<[_username: string], [void], "nonpayable">;

  usernames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  viewBoard: TypedContractMethod<[matchId: string], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimTimeoutVictory"
  ): TypedContractMethod<[matchId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<[matchId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMatchInfo"
  ): TypedContractMethod<
    [matchId: string],
    [[string, string, boolean, boolean, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUsername"
  ): TypedContractMethod<[player: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[matchId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "movePiece"
  ): TypedContractMethod<
    [matchId: string, from: BigNumberish, to: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUsername"
  ): TypedContractMethod<[_username: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usernames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "viewBoard"
  ): TypedContractMethod<[matchId: string], [string[]], "view">;

  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameJoined"
  ): TypedContractEvent<
    GameJoinedEvent.InputTuple,
    GameJoinedEvent.OutputTuple,
    GameJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MoveCommitted"
  ): TypedContractEvent<
    MoveCommittedEvent.InputTuple,
    MoveCommittedEvent.OutputTuple,
    MoveCommittedEvent.OutputObject
  >;
  getEvent(
    key: "UsernameSet"
  ): TypedContractEvent<
    UsernameSetEvent.InputTuple,
    UsernameSetEvent.OutputTuple,
    UsernameSetEvent.OutputObject
  >;

  filters: {
    "GameCreated(string,address)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameJoined(string,address,address)": TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;
    GameJoined: TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;

    "MoveCommitted(string,address,uint8,uint8)": TypedContractEvent<
      MoveCommittedEvent.InputTuple,
      MoveCommittedEvent.OutputTuple,
      MoveCommittedEvent.OutputObject
    >;
    MoveCommitted: TypedContractEvent<
      MoveCommittedEvent.InputTuple,
      MoveCommittedEvent.OutputTuple,
      MoveCommittedEvent.OutputObject
    >;

    "UsernameSet(address,string)": TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;
    UsernameSet: TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;
  };
}
