/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  ZamaConfig,
  ZamaConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/ZamaConfig";

const _abi = [
  {
    inputs: [],
    name: "ZamaProtocolUnsupported",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220adf85da474c9c8165e178133ee35e60bb4e98ba6832bd5be43e3e0837199c78b64736f6c63430008180033";

type ZamaConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ZamaConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ZamaConfig__factory extends ContractFactory {
  constructor(...args: ZamaConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ZamaConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ZamaConfig__factory {
    return super.connect(runner) as ZamaConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ZamaConfigInterface {
    return new Interface(_abi) as ZamaConfigInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ZamaConfig {
    return new Contract(address, _abi, runner) as unknown as ZamaConfig;
  }
}
